### ISSUE TITLE
Allure 2.9.0 cannot work with testng 7.0.0

### ISSUE THREAD

**Issue by derinbay** [allure-framework/allure2#890]
**Describe the bug**
If you use testng 7.0.0 (still in beta), allure 2.9.0 throws an exception

**To Reproduce**
1. Update your testng to 7.0.0 if your not using
2. Update your allure to 2.9.0
3. Run a test

    Test ignored.
java.lang.NoSuchMethodError: org.testng.internal.TestResult.<init>(Ljava/lang/Object;Lorg/testng/ITestNGMethod;Ljava/lang/Throwable;Lorg/testng/ITestContext;)V
	at io.qameta.allure.testng.AllureTestNg.createFakeResult(AllureTestNg.java:171)
	at io.qameta.allure.testng.AllureTestNg.lambda$onStart$1(AllureTestNg.java:167)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.qameta.allure.testng.AllureTestNg.onStart(AllureTestNg.java:167)
	at org.testng.TestRunner.fireEvent(TestRunner.java:898)
	at org.testng.TestRunner.beforeRun(TestRunner.java:612)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

| Allure version | 2.9.0 |
| --- | --- |
| Test framework | testng@7.0.0-beta3 |
| Allure adaptor | allure-testng@2.9.0 |
